substitutions:
  device_name: LiFire
  device_id: lifire
  project_name: juju.lifire
  project_version: "0.1"
  default_update_interval: 30s
  sleep_duration: 120s

packages:
  api:
    api:
      on_client_connected:
      # Update the important sensors.
      - component.update: uptime0
      - component.update: battery_voltage
      # Sleep to ensure the updates go through.
      - delay: 1s
      - deep_sleep.enter:
          id: deep_sleep0
          # Sleep until the start of the next cycle. Note that `sleep_duration` is in ms.
          sleep_duration: !lambda |-
            auto now = id(homeassistant_time).now().timestamp;
            return (std::ceil(now/300.0)*300 - now) * 1e3;

<<: !include firebeetle2.yaml
